# You have to download TEDLIUM "online nnet2" models in order to use this sample
# Run download-tedlium-nnet2.sh in 'test/models' to download them.
use-nnet2: True
decoder:
    # All the properties nested here correspond to the kaldinnet2onlinedecoder GStreamer plugin properties.
    # Use gst-inspect-1.0 ./libgstkaldionline2.so kaldinnet2onlinedecoder to discover the available properties
    nnet-mode: 3
    use-threaded-decoder:  true
    model : /home/ubuntu/kaldi/egs/aspire/s5/exp/tdnn_7b_chain_online/final.mdl
    word-syms : /home/ubuntu/kaldi/egs/aspire/s5/exp/tdnn_7b_chain_online/graph_pp/words.txt
    fst : /home/ubuntu/kaldi/egs/aspire/s5/exp/tdnn_7b_chain_online/graph_pp/HCLG.fst
    mfcc-config : /home/ubuntu/kaldi/egs/aspire/s5/exp/tdnn_7b_chain_online/conf/mfcc.conf
    ivector-extraction-config : /home/ubuntu/kaldi/egs/aspire/s5/exp/tdnn_7b_chain_online/conf/ivector_extractor.conf
    frame-subsampling-factor: 3
    max-active: 7000
    beam: 15.0
    lattice-beam: 6.0
    acoustic-scale: 1.0
    do-endpointing : true
    endpoint-silence-phones : "1:2:3:4:5:6:7:8:9:10"
    traceback-period-in-secs: 0.5
    chunk-length-in-secs: 0.25
    num-nbest: 3
    #Additional functionality that you can play with:
    #lm-fst:  test/models/english/tedlium_nnet_ms_sp_online/G.fst
    #big-lm-const-arpa: test/models/english/tedlium_nnet_ms_sp_online/G.carpa
    #phone-syms: /home/ubuntu/kaldi/egs/aspire/s5/exp/tdnn_7b_chain_online/graph_pp/phones.txt
    word-boundary-file: /home/ubuntu/kaldi/egs/aspire/s5/exp/tdnn_7b_chain_online/graph_pp/phones/word_boundary.int
    #do-phone-alignment: true
out-dir: tmp

use-vad: True
silence-timeout: 10

# Just a sample post-processor that appends "." to the hypothesis
post-processor: perl -npe 'BEGIN {use IO::Handle; STDOUT->autoflush(1);} s/(.*)/\1./;'

# A sample full post processor that add a confidence score to 1-best hyp and deletes other n-best hyps
full-post-processor: ./sample_full_post_processor.py

logging:
    version : 1
    disable_existing_loggers: False
    formatters:
        simpleFormater:
            format: '%(asctime)s - %(levelname)7s: %(name)10s: %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        console:
            class: logging.StreamHandler
            formatter: simpleFormater
            level: DEBUG
    root:
        level: CRITICAL
        handlers: [console]
